### ISSUE TITLE
Initializer

### ISSUE THREAD

**Issue by abraxascorner** [railsware/BloodMagic#21]
```objective-c
@implementation APIClient

- (instancetype)init {
    self = [super initWithBaseURL:[NSURL URLWithString:BASE_URL]];
    if (!self) {
        return nil;
    }
    
    self.responseSerializer = [AFJSONResponseSerializer serializer];
    self.requestSerializer = [AFJSONRequestSerializer serializer];
    
    return self;
}

@end

//this method is executed before main.m
__attribute__((constructor)) static void APIClientInitialazer() {
   BMInitializer *initializer = [BMInitializer injectableInitializer];
    initializer.propertyClass = [APIClient class];
    initializer.initializer = ^id (id sender) {
       static id singleInstance = nil;
        static dispatch_once_t once;
        dispatch_once(&once, ^{
            NSLog(@"%@", BASE_URL);
            singleInstance = [[APIClient alloc] initWithBaseURL:[NSURL URLWithString:BASE_URL]];
        });
       return singleInstance; __
    };
    [initializer registerInitializer];
}
```
block is never exected. Am I wrong at some step?

**Comment by AlexDenisov** [comment]
@abraxascorner it executes only on demand.
Do you inject he client into some class? If so, can you, please, show how you do it?

**Comment by abraxascorner** [comment]
In the service layer, I inject client.

@interface UserService () <BMLazy>

@property (strong, bm_lazy) APIClient *client;

@end

@implementation UserService

@dynamic client;

**Comment by abraxascorner** [comment]
@AlexDenisov maybe I didn't explain well, block inside id(sender) is not executed. BMInitializer is called as well as registerInitializer.

**Comment by AlexDenisov** [comment]
Oh, you need to change `BMLazy` to `BMInjectable`, I separated this attributes some time ago.

**Comment by abraxascorner** [comment]
Thank you, it works as a charm.

**Comment by AlexDenisov** [comment]
@abraxascorner great!

**Comment by abraxascorner** [comment]
And if I want to use and lazy and injectable, I should implement both protocols, <BMLazy, BMInjectable> ?

**Comment by AlexDenisov** [comment]
Yes, also you'd need to change the properties 'implementation' a bit, but it's easy, here is an example:

```objective-c
@interface FooBar : NSObject
  <BMLazy, BMInjectable>
// ...
@end

@implementation FooBar
@lazy(lazyProperty);
@injectable(injectableProperty);
@end
```

it needs to be done to tell the BM which attribute applies to which property.

**Comment by abraxascorner** [comment]
Thank you. @AlexDenisov
