### ISSUE TITLE
NSObject protocol is forward declared in BMPreference.h, why?

### ISSUE THREAD

**Issue by DanSkeel** [railsware/BloodMagic#27]
Hello, why don't you import `#import <Foundation/NSObject.h>` [here](https://github.com/railsware/BloodMagic/blob/7a11d89e7c0fc49b83fbe7a1f256327520212027/BloodMagic/Sources/Modules/Preference/Public/BMPreference.h)?

If someone uses this header he will have to import `Foundation/NSObject.h` anyway, so why don't you import it yourself? Probably I miss some point.

You oblige developers to import `NSObject.h` before `#import <BloodMagic/Preference.h>`, otherwise, they get a compiler error.

**Comment by AlexDenisov** [comment]
Hi @DanSkeel, thank you for your feedback.

There is no specific reason why the import is omitted, just a 'typo'.
Would you mind to send a pull request?

**Comment by DanSkeel** [comment]
Yeah, sure)
