### ISSUE TITLE
Bloodmagic swaps all @dynamic properties' implementatoins

### ISSUE THREAD

**Issue by DanSkeel** [railsware/BloodMagic#30]
Hi, I don't have a clear understanding of framework, because of lack of time, but as far as I understood,
BloodMagic implements on my own all properties that are marked as `@dynamic`, no matter if I added `bm_injectable` property attribute or not. This means that I can't use `@dynamics` for my own purposes and at the same time use BloodMagic. I wish I could.

Is there a way to fix it, or the core idea of framework realization is not compatible with my wish? Sorry, once again, I tried to answer my own question, but It would be less time consuming if you give me a hint.

**Comment by AlexDenisov** [comment]
That is correct.
At the moment there is no way to tell BM which properties to avoid.
The best way is to split the class into a few classes: one affected by BM, other - not affected.

P.S. `bm_injectable` is just an empty macro definition, it was intended to improve readability, though I hardly used it.

**Comment by DanSkeel** [comment]
Ok, thanks. 
I noticed that it's an empty macro definition, but I thought maybe I just don't know some compiler magic)
